#define BUILTIN_LED 2

#define LEFT_SW_PIN 32
#define LEFT_X_PIN 12
#define LEFT_Y_PIN 13

#define RIGHT_SW_PIN 33
#define RIGHT_X_PIN 14
#define RIGHT_Y_PIN 15

#define DEBUG_BUILD
#define SAMPLING_TIME_MS 20
#define TRANSMIT_DATA_SIZE 7

#define ADDITIONAL_BUTTONS
#define LEFT_SW2_PIN 27
#define RIGHT_SW2_PIN 4
